version: '2.2'

networks:
  cupnet:

services:
  ca.cipbancos.org.br:
    container_name: ca.cipbancos.org.br
    extends:
      file: docker-compose-base.yml
      service: ca-base

  orderer.cipbancos.org.br:
    container_name: orderer.cipbancos.org.br
    extends:
      file: docker-compose-base.yml
      service: orderer-base
  
  peer0.cipbancos.org.br:
    container_name: peer0.cipbancos.org.br
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=minerva_cupnet
      - CORE_PEER_ID=peer0.cipbancos.org.br
      - CORE_PEER_ADDRESS=peer0.cipbancos.org.br:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer0.cipbancos.org.br/msp:/etc/hyperledger/msp/peer
    depends_on:
      - couchdb

  peer1.cipbancos.org.br:
    container_name: peer1.cipbancos.org.br
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=minerva_cupnet
      - CORE_PEER_ID=peer1.cipbancos.org.br
      - CORE_PEER_ADDRESS=peer1.cipbancos.org.br:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer1.cipbancos.org.br/msp:/etc/hyperledger/msp/peer
    depends_on:
      - couchdb

  couchdb:
    container_name: couchdb
    extends:
      file: docker-compose-base.yml
      service: couchdb-base
  
  cli:
    container_name: cli
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    extends:
      file: docker-compose-base.yml
      service: cli-base
  
  webapp:
    container_name: webapp
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    extends:
      file: docker-compose-base.yml
      service: webapp-base
    environment:
      - WEBAPP_USERAPPPATH=/usr/local/minerva/
      #- WEBAPP_PEER=peer0.cipbancos.org.br
      - WEBAPP_PEER_PORT=7051
      - WEBAPP_PORT_EVENTHUB=7053
    ports:
      - 8081:8080
      #- 8888:8888 #debug port
    volumes:
      - ./webapp-volume-peer/minerva:/usr/local/minerva/
      - ./webapp-volume-peer/h2db:/root