version: '2.4'

services:
  ca-base:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.cipbancos.org.br
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cipbancos.org.br-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0b2cdb5133fbad7270f446d9715923bf9faa35875a676ad734d8010523df65c9_sk
    ports:
      - "7054:7054"
    volumes:
      - ./config/scripts-ca/:/scripts
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'chmod +x /scripts/start.sh && /scripts/start.sh'
    networks:
      - cupnet
  
  orderer-base:
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: sh -c 'chmod +x /scripts/start.sh && /scripts/start.sh && orderer'
    ports:
      - 7050:7050
    volumes:
      - ./config/scripts-orderer/:/scripts
      - ./config/config/:/etc/hyperledger/configtx
      - ./config/crypto-config/ordererOrganizations/cipbancos.org.br/orderers/orderer.cipbancos.org.br/:/etc/hyperledger/msp/orderer
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer0.cipbancos.org.br/:/etc/hyperledger/msp/peerCIP
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer1.cipbancos.org.br/:/etc/hyperledger/msp/peerCIP
    networks:
      - cupnet

  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=CIPMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cup_cup
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    volumes:
      - /var/run/:/host/var/run/
      # - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer0.cipbancos.org.br/msp:/etc/hyperledger/msp/peer
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/users:/etc/hyperledger/msp/users
      - ./config/config:/etc/hyperledger/configtx
      - ./chaincode/:/opt/gopath/src/github.com/
    networks:
      - cupnet
  
  couchdb-base:
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - cupnet
  
  cli-base:
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.cipbancos.org.br:7051
      - CORE_PEER_LOCALMSPID=CIPMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cipbancos.org.br/users/Admin@cipbancos.org.br/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/
      - ./config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - cupnet

  webapp-base:
    build:
      dockerfile: ./tomcat.dockerfile
      context: .
    image: fmesquita92/tomcat
    environment:
      - GOPATH=/opt/gopath    
    volumes:
      - ./webapp-volume/webapps:/usr/local/tomcat/webapps
    networks:
      - cupnet